---
env:
  browser: true
  node: true
  es2020: true
  jest/globals: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - prettier
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:jest/recommended
  - prettier/@typescript-eslint
rules:
  prettier/prettier: error
